### PR TITLE
Fix RIL (thanks to @wakaber for his RIL class)

### PR DESCRIPTION
**Pull request by ngoquang2708**

### CODE REVIEW

**Comment by koquantam** [comment]
Did it fully working?

**Comment by koquantam** [comment]
Alright, confirmed by a factory reset

**Comment by ngoquang2708** [comment]
I patched the SamsungSPRDRIL class based on his SamsungBCMRIL and it is working now. These two RIL seems identical.

**Comment by koquantam** [comment]
And 2nd SIM signals?....

**Comment by ngoquang2708** [comment]
No further process, just like before.

**Comment by wakaber** [comment]
Her*

**Comment by koquantam** [comment]
LOL.... really?
Now i know there's a girl whose devs android :D
OK, stop this. How did you get dual-SIM signals working? or it works by default? @wakaber

**Comment by ngoquang2708** [comment]
@wakaber: Ouch, sorry!

**Comment by wakaber** [comment]
yep xD
They work(ed) ( i broke my display :< ) by default on my phone with this RIL. This could be related to init scripts and rild sockets. 
Try renaming rild1 to rild2 and i'm not sure why there's third socket, it'd only be needed if device had 3 sims.

`service ril-daemon3 /system/bin/rild -l /system/lib/libreference-ril_sp.so -m w -n 2
    class core
    socket rild2 stream 660 root radio
    socket rild-debug2 stream 660 radio system
    disabled
    user root
    group radio cache inet misc audio sdcard_rw log shell sdcard_r`

Also try this patch https://gist.github.com/wakaber/38664c004654079e8262

**Comment by koquantam** [comment]
Can you try it dude?
I'm still compiling with some experiments

**Comment by koquantam** [comment]
Maybe @wakaber said right
Did you notice (for mine) "VIETTEL | No service - VIETTEL" on notif drawer?

**Comment by ngoquang2708** [comment]
Actually, those rils daemon is managed by modemd service, and modemd starts rild daemons based on the value of ril.modem.w.count, which is value of 2 in system.prop.
I've observed that there is a ril deamon crashing when the phone booting, I guess that this ril managed sim 2. I will do some investigation later when I have time.

**Comment by ngoquang2708** [comment]
@koquantam: I have all of "NO SERVICE".

**Comment by koquantam** [comment]
Well, did you out-comment the RIL class?
That causes phone call stuck and no service

**Comment by koquantam** [comment]
If you said ril-daemon3 manages SIM 2, then why there's 3 ril-daemons?

**Comment by ngoquang2708** [comment]
It is supported to do that in order to use our  RIL class!

**Comment by ngoquang2708** [comment]
About ril daemon 3, it is just a place holder

**Comment by ngoquang2708** [comment]
Needs to cleanup those *.rc scripts.

**Comment by koquantam** [comment]
Hmm... do you mean this above?
In init.scx15.rc
on property:ro.modem.w.count=2
    write /proc/sim/0 w
    write /proc/sim/1 w

**Comment by ngoquang2708** [comment]
Likely it.

**Comment by koquantam** [comment]
In fact, there's no such /proc/sim
Typos maybe?
Gonna do some experiments now

**Comment by koquantam** [comment]
Hah, disable 3rd daemon makes RIL crashes

**Comment by koquantam** [comment]
OK, got results now
Stock init binary makes RIL works without workaround, so the main problem is out init binary

**Comment by ngoquang2708** [comment]
I will try it.

**Comment by koquantam** [comment]
[boot.img.zip](https://github.com/koquantam/android_device_samsung_vivalto3gvn/files/114047/boot.img.zip)

**Comment by ngoquang2708** [comment]
Yeah, this is faster, million thanks!

**Comment by koquantam** [comment]
Well, let's thanks to Kitchen :D

**Comment by koquantam** [comment]
By looking at getprop | grep svc, i see there're bunches of services that is running
Let's see if increasing services counts works

**Comment by ngoquang2708** [comment]
Did you do any modification to the boot.img or just replace init exe?

**Comment by koquantam** [comment]
Only init binary
You can check if there's any modification

**Comment by ngoquang2708** [comment]
Confirmed

**Comment by ngoquang2708** [comment]
Well, got this with CM init:
```
<11>[    8.006763] C0 [           init, 1] init: sys_prop: permission denied uid:1000  name:ril.sim2.present
```

**Comment by koquantam** [comment]
IDK, try googling it

**Pull request merged**
