### PR TITLE
Update.

### PR DESCRIPTION
**Pull request by ngoquang2708**

### CODE REVIEW

**Comment by ngoquang2708** [comment]
Do you have any idea about who manage this repo https://github.com/vivalto/android_device_samsung_vivalto3gvn.

**Comment by koquantam** [comment]
IDK. I've sent them a bunch of fixes but nothing changed

**Comment by ngoquang2708** [comment]
So you do your own repo instead of forking them?

**Comment by koquantam** [comment]
Yes, i am.
I think the owner of that repo is so busy so i decided to make my own repo and working for it.
Building this rom is so slow with a Pentium :)

**Comment by ngoquang2708** [comment]
But it is fun, too!

**Pull request merged**
