### PR TITLE
Fix sim2 data subscription

### PR DESCRIPTION
**Pull request by ngoquang2708**

### CODE REVIEW

**Comment by ngoquang2708** [comment]
Please reopen this, then test it to see if it works with you.

**Comment by koquantam** [comment]
Err... conflicts?

**Comment by ngoquang2708** [comment]
Revert your commit first.

**Comment by ngoquang2708** [comment]
Would you like to use prebuilt webviewchromium? I will send a PR.

**Comment by koquantam** [comment]
I've seen your tree, and already done it before :D

**Comment by ngoquang2708** [comment]
Yeah, but nothing in cm-11.0 tree.

**Comment by koquantam** [comment]
OK, i'll get your PR

**Comment by koquantam** [comment]
Damn, have to use GitHub Desktop

**Comment by ngoquang2708** [comment]
``` GitHub Desktop``` first time heard about it.

**Comment by koquantam** [comment]
Well, it's for Windows only. I dual boot W10  and Ubuntu 14.04 through.

**Pull request merged**
