### PR TITLE
HAL: add hwcomposer source code

### PR DESCRIPTION
**Pull request by ngoquang2708**

### CODE REVIEW

**Comment by koquantam** [comment]
Hmm... can you switch this to CM12.1?
CM11 is stable now btw

**Comment by ngoquang2708** [comment]
You can merge it, then cherry-pick this and gralloc to cm-12.1.

**Comment by koquantam** [comment]
How to cherry-pick in git?

**Comment by ngoquang2708** [comment]
Switch to cm-11.0 branch, ```git log``` to search for gralloc and hwcomposer commit hash, save it else where. Switch to cm-12.1, ```git cherry-pick [gralloc hash]```, do the same for hwcomposer.

**Comment by koquantam** [comment]
OK, thanks

**Pull request merged**
