### PR TITLE
Update.

### PR DESCRIPTION
**Pull request by ngoquang2708**

### CODE REVIEW

**Comment by koquantam** [comment]
sorry, please re-add the commit this. I got a big problem with my branch

**Comment by ngoquang2708** [comment]
Please rename your master branch to cm-11.0

**Comment by koquantam** [comment]
Ok, renamed

**Comment by koquantam** [comment]
OH, damn. Deleted it once more. Could you please re-add the commit once more?

**Comment by ngoquang2708** [comment]
Can you reopen this pull request?

**Comment by koquantam** [comment]
LOL, it's grayed out

**Comment by ngoquang2708** [comment]
github says we have an entire different history and I do not know what to do, I am not familiar with github or git much :)

**Comment by koquantam** [comment]
Me too man. So i guess you've to redo the whole pull requests.

**Comment by ngoquang2708** [comment]
OK, I will do it later. I need some sleep right now :D

**Comment by koquantam** [comment]
Do you've any ideas about these logcats? I get a bunch of process terminated

**Comment by ngoquang2708** [comment]
Pastebin your logcat here

**Comment by koquantam** [comment]
Pastebin got 404, so i use this instead.
https://pastee.org/zavtm

**Comment by ngoquang2708** [comment]
I think it relates to these errors:

E/cutils  (  508): Not a directory: /storage/sdcard0
E/dalvikvm(  508): cannot mountExternalStorage(): Invalid argument

You have a misconfiguration of storage_list.xml overlay. See my fork for fixes.

**Comment by ngoquang2708** [comment]
I will send a pull req now though.

**Comment by koquantam** [comment]
oh yeah, i see. adb shell mount only show FUSE sdcard in /mnt/shell/emulated
Going to fix this now

**Comment by koquantam** [comment]
I think you should remove /storage/sdcard0 internal mountpoint, because it's symlinked

**Comment by ngoquang2708** [comment]
You are right.

**Comment by koquantam** [comment]
Still has that error.

**Comment by ngoquang2708** [comment]
Post your logcat so that I can see.

**Comment by koquantam** [comment]
https://pastee.org/za7cn

**Comment by ngoquang2708** [comment]
Run mount as root and post it contents here, please.

**Comment by ngoquang2708** [comment]
My source is still compiling!

**Comment by koquantam** [comment]
LOL, that's the apk error.

**Comment by ngoquang2708** [comment]
I know. Android runtime is trying to access that folder an it failed. That cause its crash.

**Comment by koquantam** [comment]
Wifi's still dead. It detects the network but can't connect

**Comment by ngoquang2708** [comment]
Yeah. I faced that too.

**Comment by ngoquang2708** [comment]
I glad that it can boot into UI. More works to do.

**Comment by koquantam** [comment]
It's framework-res.apk error. Tried s5830i's one and apps start dexing.
Going to decompile that apk to fix the storage_list.xml

**Comment by koquantam** [comment]
Nope, i tried another framework-res.apk (taken from another cm11)
The problem is the storage. It prevents apps to start.

**Comment by ngoquang2708** [comment]
/dev/fuse /mnt/shell/emulated fuse rw,nosuid,nodev,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0

This line shows that sdcard daemon is start correctly. It seems that that problem is in android runtime part. It cannot bind /mnt/shell/emulated/0 to /storage/emulated/0 (internal storage)

**Comment by koquantam** [comment]
/storage/emulated/0 doesn't exist, so how can it do bind mount?

**Comment by ngoquang2708** [comment]
Check to see if you can access  /mnt/shell/emulated, or create a file on it. That dir is also a bind mount from /data/media. So if /data/media does not exist or it permissions is not set correctly, it will cause sdcard daemon to confuse.

**Comment by ngoquang2708** [comment]
That android runtime part.

**Comment by koquantam** [comment]
root@vivalto3gvn:/ # mkdir /mnt/shell/emulated/12
root@vivalto3gvn:/ # ls -la /mnt/shell/emulated
drwxrwx--x root     sdcard_r          2016-01-07 19:04 0
drwxrwx--x root     sdcard_r          2016-01-07 21:50 12
drwxrwx--x root     sdcard_r          2016-01-07 19:06 obb

**Comment by ngoquang2708** [comment]
You are able to create a folder on it, so check /data/media to see if there is that folder you have created too?

**Comment by koquantam** [comment]
root@vivalto3gvn:/ # ls -la /data/media
drwxrwx--- media_rw media_rw          2016-01-07 19:04 0
drwxrwxr-x media_rw media_rw          2016-01-07 21:50 12
drwxrwxr-x media_rw media_rw          2016-01-07 19:06 obb
root@vivalto3gvn:/ #

**Comment by ngoquang2708** [comment]
My build is almost done. Wait for sooo looong...

**Comment by koquantam** [comment]
LOL, for me 6hrs is enough for a G630 with 4GB of ram and 6GB zram.

**Comment by ngoquang2708** [comment]
It's wired. Why there is no /storage/emulated/0????

**Comment by ngoquang2708** [comment]
Yeah, 6hrs and about 200G of your disk space. OMG.

**Comment by koquantam** [comment]
Hey, it booted up, UI shown now.
Remove "symlink /storage/emulated/legacy /storage/sdcard0" in init.vivalto3gvn_base.rc
IDK why samsung make a symlink for that.

**Comment by koquantam** [comment]
Gotta get some sleeps now :)
Anyway, please try your own source and left some results.

**Comment by ngoquang2708** [comment]
OK

**Comment by koquantam** [comment]
Now we have a lot of things to do
The most important now is RIL
I know the libpath but libargs doesn't

**Comment by ngoquang2708** [comment]
Sleep, man.

**Comment by ngoquang2708** [comment]
init.board.rc it not come from stock, and that is the cause of internal storage problem.

**Comment by ngoquang2708** [comment]
libhardware_legacy in cm11 is broken. I'd there any ways to backport it from cm12.1?

**Comment by ngoquang2708** [comment]
Broken in WiFi.

**Comment by koquantam** [comment]
Better rebuild it.
About wifi, there're missing blobs compared with stock. Please check and re-add blobs

**Comment by koquantam** [comment]
If call never ends, change SELinux to Permissive (Idk this is the problem)

**Pull request closed without merging**
